cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:offer_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<int:cart_item_id>', views.update_number_of_people, name='update_number_of_people'),
    path('remove/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('checkout', views.checkout, name='checkout'),
]

flyboredome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('testimonials/', include('testimonials.urls')),
    path('owner/', include('owner_admin.urls')),
    path('', include('offers.urls')),
    path('cart/', include('cart.urls')),
    path('auth/', include('authentication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

from owner_admin.models import Offers


class OfferItem(models.Model):
    offer = models.ForeignKey(Offers, on_delete=models.CASCADE)
    number_of_people = models.PositiveIntegerField(default=1)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.username}'s cart"
    
    def calculate_total_cost(self):
        total_cost = 0
        for cart_item in self.cartitem_set.all():
            total_cost += cart_item.offer.price * cart_item.number_of_people
        return total_cost

    def book(self, participantDict):
        # Calculate total cost
        total_cost = self.calculate_total_cost()
        
        # Create a new booking instance
        booking = Booking(user=self.user, total_cost=total_cost)
        booking.save()
        
        # Loop through all cart items and create booking items for each
        for cart_item in self.cartitem_set.all():
            booking_item = BookingItem(offer=cart_item.offer, number_of_people=cart_item.number_of_people, booking=booking)
            booking_item.offer.spots_available -= booking_item.number_of_people
            booking_item.offer.save()
            booking_item.save()
            booking_participants = participantDict[cart_item.id]
            # Loop through all booking participants and create a booking participant for each
            for participant in booking_participants:
                booking_participant = BookingParticipant(booking_item=booking_item, first_name=participant['first_name'], last_name=participant['last_name'], email=participant['email'], phone_number=participant['phone_number'])
                booking_participant.save()

        # Delete the cart after converting it to a booking
        self.delete()


class CartItem(OfferItem):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    offer = models.ForeignKey(Offers, on_delete=models.CASCADE)
    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        return f"{self.offer.offer} offer for {self.number_of_people} in {self.cart}"


class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    total_cost = models.DecimalField(max_digits=8, decimal_places=2, validators=[MinValueValidator(0)])
    
    def __str__(self):
        return f"{self.user.username}'s booking for {self.date_created}"


class BookingItem(OfferItem):
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        return f"{self.offer.offer} offer for {self.number_of_people} in {self.booking}"


class BookingParticipant(models.Model):
    booking_item = models.ForeignKey(BookingItem, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.first_name} {self.last_name} for {self.booking_item}"

cart/views.py
import json
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import requests
from decimal import Decimal
from .models import Cart, CartItem
from owner_admin.models import Offers

@login_required
def view_cart(request):
    cart = Cart.objects.filter(user=request.user).first()
    if not cart:
        cart = Cart(user=request.user)
        cart.save()
    cart_items = cart.cartitem_set.all()
    total_cost = cart.calculate_total_cost()
    context = {'cart_items': cart_items, 'total_cost': total_cost}
    return render(request, 'cart/view_cart.html', context)

@login_required
def add_to_cart(request, offer_id):
    offer = Offers.objects.get(id=offer_id)
    number_of_people = int(request.POST.get('number_of_people', 1))
    if number_of_people <= 0:
        messages.error(request, 'Invalid number of people.')
        return redirect('cart:view_cart')
    cart = Cart.objects.filter(user=request.user).first()
    if not cart:
        cart = Cart(user=request.user)
        cart.save()
    cart_item, created = CartItem.objects.get_or_create(cart=cart, offer=offer)
    if not created:
        cart_item.number_of_people += number_of_people
        cart_item.save()
    else:
        cart_item.number_of_people = number_of_people
        cart_item.save()
    messages.success(request, f"{offer.offer} offer added to cart.")
    return redirect('cart:view_cart')

@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(id=cart_item_id)
    cart_item.delete()
    messages.success(request, f"{cart_item.offer.offer} offer removed from cart.")
    return redirect('cart:view_cart')

@login_required
def update_number_of_people(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id, cart__user=request.user)
    if request.method == 'POST':
        number_of_people = int(request.POST.get(f'number_of_people_{cart_item_id}', 0))
        if number_of_people > 0:
            cart_item.number_of_people = number_of_people
            cart_item.save()
            messages.success(request, f'Number of people for {cart_item.offer.offer} updated to {number_of_people}.')
        else:
            messages.warning(request, f'Number_of_people must be greater than 0 for {cart_item.offer.offer}.')
        return redirect('cart:view_cart')

@login_required
def checkout(request):
    try:
        cart = Cart.objects.filter(user=request.user).first()
        if not cart:
            messages.warning(request, "Your cart is empty.")
            return redirect('cart:view_cart')
        
        # Get the conversion rates from the API
        response = requests.get('https://api.exchangerate-api.com/v4/latest/CAD')
        if not response.ok:
            messages.error(request, "Unable to get the conversion rates.")
            return redirect('cart:view_cart')
        conversion_rates = json.dumps(response.json()["rates"])
        
        if request.method == 'POST':
            participantDict = {}
            for item in cart.cartitem_set.all():
                participants = []
                for i in range(item.number_of_people):
                    first_name = request.POST.get(f"first_name_{item.id}_{i+1}")
                    last_name = request.POST.get(f"last_name_{item.id}_{i+1}")
                    email = request.POST.get(f"email_{item.id}_{i+1}")
                    phone = request.POST.get(f"phone_{item.id}_{i+1}")
                    try:
                        validate_email(email)
                        newObj = {"first_name":first_name, "last_name":last_name, "email":email, "phone_number":phone}
                        participants.append(newObj)
                    except ValidationError:
                        messages.error(request, f"{email} is not a valid email address. Try again")
                        return redirect('cart:view_cart')
                participantDict[item.id] = participants
                cart.book(participantDict)
                messages.success(request, "Booking successful! Thank you.")
                return redirect('cart:view_cart')
            
        context = {'total_cost': cart.calculate_total_cost(), 'cart_items': cart.cartitem_set.all(), 'conversion_rates': conversion_rates}
        return render(request, 'cart/checkout.html', context)
    
    except Exception as e:
        messages.error(request, str(e))
        return redirect('cart:view_cart')

cart/templates/cart/checkout.html
{% extends 'base.html' %}
{% load filters %}
{% block content %}
<div class="container py-5">
	<h1 class="text-center mb-4">Checkout</h1>
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<form method="post">
				{% csrf_token %}
				{% for item in cart_items %}
				<div class="accordion mb-4" id="accordion-{{ item.id }}">
					<div class="accordion-item">
						<h2 class="accordion-header" id="heading-{{ item.id }}">
							<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-{{ item.id }}" aria-expanded="true" aria-controls="collapse-{{ item.id }}">
							{{ item.offer.offer }} for {{item.number_of_people}} {% if item.number_of_people == 1 %}person{% else %}people{% endif %}
							</button>
						</h2>
						<div id="collapse-{{ item.id }}" class="accordion-collapse collapse show" aria-labelledby="heading-{{ item.id }}" data-bs-parent="#accordion-{{ item.id }}">
							<div class="accordion-body">
								{% for i in item.number_of_people|range %}
								<h2 class="card-title mb-0">Participant {{ forloop.counter }}</h2>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group mb-3">
											<label for="first_name_{{ item.id }}_{{ i }}">First Name</label>
											<input required type="text" maxlength="100" class="form-control" id="first_name_{{ item.id }}_{{ i }}" name="first_name_{{ item.id }}_{{ i }}">
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group mb-3">
											<label for="last_name_{{ item.id }}_{{ i }}">Last Name</label>
											<input required type="text" maxlength="100" class="form-control" id="last_name_{{ item.id }}_{{ i }}" name="last_name_{{ item.id }}_{{ i }}">
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group mb-3">
											<label for="email_{{ item.id }}_{{ i }}">Email</label>
											<input required type="email" class="form-control" id="email_{{ item.id }}_{{ i }}" name="email_{{ item.id }}_{{ i }}">
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group mb-3">
											<label for="phone_{{ item.id }}_{{ i }}">Phone Number</label>
											<input required type="tel" maxlength="20" class="form-control" id="phone_{{ item.id }}_{{ i }}" name="phone_{{ item.id }}_{{ i }}">
										</div>
									</div>
								</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				<div class="row">
					<div class="col-md-6 mb-3">
						<label for="currency" class="form-label">Currency</label>
						<select class="form-select" name="currency" id="currency">
							<option value="CAD" selected>CAD - Canadian Dollar</option>
							<option value="USD">USD - US Dollar</option>
							<option value="EUR">EUR - Euro</option>
						</select>
					</div>
					<div class="col-md-6 mb-3">
						<label for="total" class="form-label">Total</label>
						<input type="text" class="form-control" id="total" name="total" value="{{ total_cost }}" readonly disabled>
					</div>
				</div>
				<button type="submit" class="btn btn-primary">Submit Order</button>
			</form>
		</div>
	</div>
</div>
<script>
	const currencySelect = document.getElementById("currency");
	// add an event listener for when the select element changes
	currencySelect.addEventListener("change", function(event) {
	  // get the selected currency
	  const selectedCurrency = event.target.value;
	  const conversionRates = JSON.parse('{{conversion_rates|escapejs}}');
	  // get the actual total
	  const actualTotal = parseFloat('{{total_cost}}');
	  // get the conversion rate for the selected currency
	  const conversionRate = conversionRates[selectedCurrency];
	  // calculate the converted total
	  const convertedTotal = (actualTotal * conversionRate).toFixed(2);
	  // set the value of the total input to the converted total
	  document.getElementById("total").value = convertedTotal;
	});
</script>
{% endblock %}

cart/templates/cart/view_cart.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-5">Your Cart</h1>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% if cart_items %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Offer</th>
                <th scope="col">Price</th>
                <th scope="col">Number of people</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for cart_item in cart_items %}
            <form method="POST" action="{% url 'cart:update_number_of_people' cart_item.id %}">
                {% csrf_token %}
                <tr>
                    <td><div class="container">{{ cart_item.offer.offer }}</div></td>
                    <td><div class="container">{{ cart_item.offer.price }}</div></td>
                    <td>
                        <div class="input-group input-group-sm">
                            <input type="number" min="1" max="{{cart_item.offer.spots_available}}" class="form-control-sm" onchange="checkPeopleChange(event, '{{cart_item.number_of_people}}')" class="form-control" name="number_of_people_{{cart_item.id}}" id="number_of_people_{{cart_item.id}}" value="{{ cart_item.number_of_people }}">
                            <button disabled id="change_number_of_people_{{cart_item.id}}" type="submit" class="btn btn-outline-secondary">Update</button>
                        </div>
                    </td>
                    <td>
                        <a href="{% url 'cart:remove_from_cart' cart_item.id %}" class="btn btn-danger btn-sm">Remove</a>
                    </td>
                </tr>
            </form>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <th scope="row">Total</th>
                <td>{{ total_cost }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <a href="{% url 'cart:checkout' %}" class="btn btn-success float-end">Checkout</a>
    {% else %}
    <p>Your cart is empty.</p>
    {% endif %}
	<script>
		function checkPeopleChange(event, oldQuantity){
			const newQuantity = event.target.value;
			const elem = document.getElementById("change_"+event.target.name);
			if(newQuantity === oldQuantity){
				elem.disabled = true;
			}else{
				elem.disabled = false;
			}
		}
	</script>
</div>
{% endblock %}