cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:offer_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<int:cart_item_id>', views.update_number_of_people, name='update_number_of_people'),
    path('remove/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('checkout', views.checkout, name='checkout'),
]

flyboredome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('testimonials/', include('testimonials.urls')),
    path('owner/', include('owner_admin.urls')),
    path('', include('offers.urls')),
    path('cart/', include('cart.urls')),
    path('auth/', include('authentication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testimonials/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views 

app_name = 'testimonials'

urlpatterns = [
    path('', views.TestimonialListView.as_view(), name="list-testimonials"),
    path('add/', login_required(views.CreateTestimonialView.as_view()), name="add-testimonial"),
]

testimonials/models.py
from django.db import models
from django.conf import settings


class Testimonial(models.Model):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=50)
    testimonial = models.TextField()
    # photo = models.ImageField(upload_to='photos',null=True,blank=True)   
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-date_added']        

    def __str__(self):
        return self.title    


class Photos(models.Model):
    testimonial = models.ForeignKey(Testimonial, on_delete=models.CASCADE, related_name="photos")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/%H/%M/%S/', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']        

    

testimonials/forms.py
from django import forms

from testimonials.models import Testimonial


class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = '__all__'

testimonials/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from .models import Testimonial, Photos

from django.views.generic import CreateView
from django.views.generic.list import ListView
from django.urls import reverse


class TestimonialListView(ListView):
    model = Testimonial
    template_name = 'testimonials/list_testimonials.html'


# LoginRequiredMixin
class CreateTestimonialView(CreateView):
    'View to create testimonials'
    model = Testimonial
    template_name = 'testimonials/testimonial_form.html'
    fields = '__all__'

    def form_valid(self, form):
        instance = form.save()
        images = self.request.FILES.getlist('images')
        for image in images:
            Photos.objects.create(testimonial=instance, photo=image)

        return super(CreateTestimonialView, self).form_valid(form)

    def get_success_url(self):
        return reverse('testimonials:list-testimonials')

testimonials/templates/testimonials/list_testimonials.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container py-4">
        <div class="row justify-content-between">
            <div class="col-3">
                <h2>
                    Testimonial List
                </h2>
            </div>
            {% if user.is_authenticated %}
            <div class="col-3">
                <a href="{% url 'testimonials:add-testimonial' %}" class="btn btn-primary">
                    <i class="bi bi-plus"></i>
                    Add
                </a>
            </div>
            {% endif %}
        </div>
        
        {% if testimonial_list %}
            <div class="row row-cols-1 row-cols-md-4 g-4">
                {% for testimonial in testimonial_list %}
                    <div class="card p-0 mt-5" style="width: 18rem; margin-right: 2rem;">
                        {% if testimonial.photos.all %}
                            <img src="{{ testimonial.photos.all.0.photo.url }}" class="card-img-top" width="200"
                                 height="200" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ testimonial.title }}</h5>
                            <p class="card-text">{{ testimonial.testimonial|truncatechars:100 }}</p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Location: {{ testimonial.location }}</small>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h2>No Testimonials Yet</h2>
        {% endif %}
    </div>
{% endblock %}

testimonials/templates/testimonials/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mutliple Upload</title>
    <style>
        img {
            height: 200px;
            width: 200px;
        }
    </style>
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="images" multiple>
        <button>Upload</button>
    </form>
    <hr>
    {% for img in images %}
    <img src="{{img.images.url}}" alt="Image">
    {% endfor %}
</body>
</html>

testimonials/templates/testimonials/testimonial_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div class="card mt-5 card-border">
                    <h2 class="m-3">Where did you come from, where did you go? Tell us what you thought of it!</h2>
                    <div class="card-body">
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="mb-3">
                                <label for="formFile" class="form-label">Upload an image</label>
                                <input class="form-control" type="file" name="images">
                            </div>
                            <button class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}