cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:offer_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<int:cart_item_id>', views.update_number_of_people, name='update_number_of_people'),
    path('remove/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('checkout', views.checkout, name='checkout'),
]

flyboredome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('testimonials/', include('testimonials.urls')),
    path('owner/', include('owner_admin.urls')),
    path('', include('offers.urls')),
    path('cart/', include('cart.urls')),
    path('auth/', include('authentication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner_admin/urls.py
from django.urls import path
from . import views

app_name = 'owner_admin'

urlpatterns = [
    path('', views.index, name='admin_home'),
    path('delete-testimonial/<int:testimonial_id>', views.delete_testimonial, name='delete_testimonial'),
    path('delete-offer/<int:offer_id>', views.delete_offer, name='delete_offer'),
    path('add-offer', views.add_or_edit_offer, name='add_offer'),
    path('edit-offer/<int:offer_id>', views.add_or_edit_offer, name='edit_offer'),
]

owner_admin/models.py
from django.db import models
from django.utils import timezone

from uuid import uuid4


class Offers(models.Model):
    offer = models.CharField(max_length=100)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date = models.DateTimeField()
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    spots_available = models.PositiveIntegerField(default=0)
    location = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if self.image:
            ext = self.image.name.split('.')[-1]
            self.image.name = f'{uuid4()}.{ext}'
        super().save(*args, **kwargs)

    def status(self):
        if self.spots_available == 0:
            return 'Sold Out'
        elif self.date > timezone.now():
            return 'Upcoming'
        elif self.date < timezone.now():
            return 'Expired'

    class Meta:
        ordering = ['-date_added']
        verbose_name_plural = 'Offers'

    def __str__(self):
        return self.offer

owner_admin/forms.py
from django import forms
from owner_admin.models import Offers


class AddOrEditOfferForm(forms.ModelForm):
    class Meta:
        model = Offers
        fields = '__all__'
        widgets = {'date_added': forms.DateInput(attrs={'hidden': True, 'readonly': True}),
                   'date': forms.DateInput(attrs={'type': 'date'})}

owner_admin/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils import timezone

from testimonials.models import Testimonial
from cart.models import BookingParticipant
from owner_admin.models import Offers
from owner_admin.forms import AddOrEditOfferForm

redirect_url = '/'


@user_passes_test(lambda u: u.is_staff, login_url=redirect_url)
def index(request):
    latest_offers = Offers.objects.order_by('-date_added')
    latest_testimonials = Testimonial.objects.order_by('-date_added')
    bookings_for_upcoming_offers = BookingParticipant.objects.filter(booking_item__offer__date__gte=timezone.now())\
        .order_by('booking_item__offer__date')
    return render(request, 'owner_admin/index.html', {'latest_testimonials': latest_testimonials,
                                                      'latest_offers': latest_offers,
                                                      'bookings_for_upcoming_offers': bookings_for_upcoming_offers})


@user_passes_test(lambda u: u.is_staff, login_url=redirect_url)
def delete_testimonial(request, testimonial_id):
    testimonial = Testimonial.objects.get(id=testimonial_id)
    testimonial.delete()
    return HttpResponseRedirect(reverse('owner_admin:admin_home'))


@user_passes_test(lambda u: u.is_staff, login_url=redirect_url)
def delete_offer(request, offer_id):
    offer = Offers.objects.get(id=offer_id)
    offer.delete()
    return HttpResponseRedirect(reverse('owner_admin:admin_home'))


@user_passes_test(lambda u: u.is_staff, login_url=redirect_url)
def add_or_edit_offer(request, offer_id=None):
    if offer_id:
        offer = Offers.objects.get(id=offer_id)
    else:
        offer = None
    if request.method == 'POST':
        form = AddOrEditOfferForm(request.POST, request.FILES, instance=offer)
        if form.is_valid():
            form.save()
            return redirect('owner_admin:admin_home')
        else:
            message = 'Please correct the error below.'
            return render(request, 'owner_admin/add_or_edit_offer.html', {'form': form, 'message': message})
    else:
        form = AddOrEditOfferForm(instance=offer)
        return render(request, 'owner_admin/add_or_edit_offer.html', {'form': form})

owner_admin/templates/owner_admin/add_or_edit_offer.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-sm-6">
            <div class="card mt-5 card-border">
                <h5 class="card-header">Add New Offer</h5>
                <div class="card-body">
                    {% if form.errors %}
                        <div class="alert alert-danger">
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if messages %}
                        <div class="alert alert-success">
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Add Offer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

owner_admin/templates/owner_admin/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="container">
        <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}"/>

        <div class="container pt-2">
            <h1>Owner Dashboard</h1>
            {#  Latest Offer Container  #}
            <div class="container border rounded mt-5 p-0">
                <div class="container-header">
                    <h2 class="m-0">Latest Offers</h2>
                    <a href="{% url "owner_admin:add_offer" %}" class="btn btn-primary top-right">
                        <i class="bi bi-plus"></i>
                        Add Offer
                    </a>
                </div>
                <div class="row scrollable container m-0 p-0">
                    <div class="row py-3" style="padding-left: 2em">
                        {% for offer in latest_offers %}
                            <div class="card p-0" style="width: 18rem; margin-right: 0.5rem;
                                margin-top: 0.5rem; margin-bottom: 0.5rem; height: 25rem">
                                {% if offer.image %}
                                    <div style="height: 10rem; overflow: hidden">
                                        <img src="{{ offer.image.url }}" class="card-img-top" alt="...">
                                    </div>
                                {% endif %}
                                <div class="card-body">
                                    <div class="detail-container">
                                        <h5 class="card-title">{{ offer.offer }}</h5>
                                        <p class="card-text">{{ offer.description|truncatechars:100 }}</p>
                                        <a class="btn btn-primary" href="{% url "owner_admin:edit_offer" offer.id %}">
                                            <i class="bi bi-pencil-fill"></i>
                                            Edit
                                        </a>
                                        <a class="btn btn-danger" style="float: right"
                                           href="{% url "owner_admin:delete_offer" offer.id %}">
                                            <i class="bi bi-trash-fill"></i>
                                            Delete
                                        </a>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <p class="card-text"><small class="text-muted">
                                        Date: {{ offer.date }}<br>
                                        Spots Available: {{ offer.spots_available }}<br>
                                    </small></p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {#  Latest Testimonials Container  #}
            <div class="container border rounded mt-4 p-0" style="overflow: hidden">
                <div class="container-header">
                    <h2>Latest Testimonials</h2>
                </div>
                <div class="row scrollable container m-0 p-0">
                    <div class="row py-3" style="padding-left: 2em">
                        {% for testimonial in latest_testimonials %}
                            <div class="card p-0" style="width: 18rem; margin-right: 0.5rem;
                            margin-top: 0.5rem; margin-bottom: 0.5rem; height: 25rem">
                                {% if testimonial.photos.all %}
                                    <div style="height: 10rem; overflow: hidden">
                                        <img src="{{ testimonial.photos.all.0.photo.url }}" class="card-img-top"
                                             alt="...">
                                    </div>
                                {% endif %}
                                <div class="card-body">
                                    <div class="detail-container">
                                        <h5 class="card-title">{{ testimonial.title }}</h5>
                                        <p class="card-text">{{ testimonial.testimonial|truncatechars:100 }}</p>
                                        <a class="btn btn-danger"
                                           href="{% url "owner_admin:delete_testimonial" testimonial.id %}">
                                            <i class="bi bi-trash-fill"></i>
                                            Delete
                                        </a>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <p class="card-text">
                                        <small class="text-muted">
                                            Location: {{ testimonial.location }}
                                        </small>
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            {#  Bookings for upcoming events  #}
            <div class="container border rounded my-4 p-0" style="overflow: hidden">
                <div class="container-header">
                    <h2>Bookings for upcoming events</h2>
                </div>
                <div class="row scrollable container m-0 p-0">
                    <div class="container m-0 p-0">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">First Name</th>
                                    <th scope="col">Last Name</th>
                                    <th scope="col">Date</th>
                                    <th scope="col">Location</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {% for booking in bookings_for_upcoming_offers %}
                                        <tr>
                                            <td>{{ booking.first_name }}</td>
                                            <td>{{ booking.last_name }}</td>
                                            <td>{{ booking.booking_item.offer.date }}</td>
                                            <td>{{ booking.booking_item.offer.location }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}