cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<int:offer_id>', views.add_to_cart, name='add_to_cart'),
    path('update/<int:cart_item_id>', views.update_number_of_people, name='update_number_of_people'),
    path('remove/<int:cart_item_id>', views.remove_from_cart, name='remove_from_cart'),
    path('checkout', views.checkout, name='checkout'),
]

flyboredome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('testimonials/', include('testimonials.urls')),
    path('owner/', include('owner_admin.urls')),
    path('', include('offers.urls')),
    path('cart/', include('cart.urls')),
    path('auth/', include('authentication.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner_admin/urls.py
from django.urls import path
from . import views

app_name = 'owner_admin'

urlpatterns = [
    path('', views.index, name='admin_home'),
    path('delete-testimonial/<int:testimonial_id>', views.delete_testimonial, name='delete_testimonial'),
    path('delete-offer/<int:offer_id>', views.delete_offer, name='delete_offer'),
    path('add-offer', views.add_or_edit_offer, name='add_offer'),
    path('edit-offer/<int:offer_id>', views.add_or_edit_offer, name='edit_offer'),
]

testimonials/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views 

app_name = 'testimonials'

urlpatterns = [
    path('', views.TestimonialListView.as_view(), name="list-testimonials"),
    path('add/', login_required(views.CreateTestimonialView.as_view()), name="add-testimonial"),
]

testimonials/models.py
from django.db import models
from django.conf import settings


class Testimonial(models.Model):
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=50)
    testimonial = models.TextField()
    # photo = models.ImageField(upload_to='photos',null=True,blank=True)   
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-date_added']        

    def __str__(self):
        return self.title    


class Photos(models.Model):
    testimonial = models.ForeignKey(Testimonial, on_delete=models.CASCADE, related_name="photos")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/%H/%M/%S/', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']        

    

testimonials/forms.py
from django import forms

from testimonials.models import Testimonial


class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = '__all__'

testimonials/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from .models import Testimonial, Photos

from django.views.generic import CreateView
from django.views.generic.list import ListView
from django.urls import reverse


class TestimonialListView(ListView):
    model = Testimonial
    template_name = 'testimonials/list_testimonials.html'


# LoginRequiredMixin
class CreateTestimonialView(CreateView):
    'View to create testimonials'
    model = Testimonial
    template_name = 'testimonials/testimonial_form.html'
    fields = '__all__'

    def form_valid(self, form):
        instance = form.save()
        images = self.request.FILES.getlist('images')
        for image in images:
            Photos.objects.create(testimonial=instance, photo=image)

        return super(CreateTestimonialView, self).form_valid(form)

    def get_success_url(self):
        return reverse('testimonials:list-testimonials')

testimonials/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <title>{% block title %}FlyBoredom{% endblock title %}</title>
</head>
<body class="vh-100 d-flex flex-column">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">FlyBoredom</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav me-auto">
                        <a class="nav-link {% if request.path == '/' %} active {% endif %}" href="{% url 'home' %}">Home</a>
                        <a class="nav-link {% if request.path == '/testimonials/' %} active {% endif %}" href="{% url 'testimonials:list-testimonials' %}">Testimonials</a>
                        {% if user.is_staff %}
                            <a class="nav-link {% if request.path == '/owner/' %} active {% endif %}" href="{% url 'owner_admin:admin_home' %}">Manage</a>
                        {% endif %}
                    </div>
                    {% if user.is_authenticated %}
                        <div class="navbar-nav">
                            <a class="nav-link {% if request.path == '/cart/' %} active {% endif %}" href="{% url 'cart:view_cart' %}">My Cart</a>
                            <a href="{% url 'signout' %}" class="nav-link">Log Out</a>
                        </div>
                    {% else %}
                        <div class="navbar-nav">
                            <a class="nav-link {% if request.path == '/auth/signin' %} active {% endif %}" href="{% url 'signin' %}">Login</a>
                            <a class="nav-link {% if request.path == '/auth/signup' %} active {% endif %}" href="{% url 'signup' %}">Register</a>
                        </div>
                    {% endif %}
            </div>
        </div>
    </nav>
    <main class="d-flex w-100 flex-grow-1">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
            crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"></script>
</body>
</html>